# Workflow for build/test/docs

name: Build

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build --if-present
        
      - name: Test
        run: npm test

  # build and publish docs
  docs:
    steps:
    - name: Checkout
      uses: actions/checkout@v2
  
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 16
    
    - name: Install
      run: npm ci

    - name: Create docs
      run: npm run docs

    - name: Publish Docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: docs